### ISSUE TITLE
Support for barrel files (index.ts)

### ISSUE THREAD

**Issue by fox1t** [beenotung/fix-esm-import-path#11] opened 2024-06-19 13:37 UTC
Hey, thanks for putting together this simple yet powerful package. It is helping us migrate from commonjs to esm in our huge monorepo.

While using it, I noticed the fix for imports from barrel files is ignored, even if the barrel file itself is correctly resolved. 
You can see in the following example:
```
[scanImport] {
  srcFile: './src/index.ts',
  importCode: "import { NodeEnv, envVariables } from './config';",
  importName: 'src/config',
  importFile: 'src/config/index.ts'
}
```

This happens specifically due to this line: https://github.com/beenotung/fix-esm-import-path/blob/master/fix-esm-import-path.js#L150

Removing it and changing the below code from:
```ts
        importCode = fixImport({
          srcFile,
          importCode,
          from: name,
          to: name + '.js',
        })
``` 
to 
```ts
        importCode = fixImport({
          srcFile,
          importCode,
          from: name,
          to:
            name +
            (importFile.startsWith(importName + '/index')
              ? '/index.js'
              : '.js'),
        })
```
fixed the issue.

Would you happen to know if the original behavior is the intended one? If so, why did you choose explicitly not to support barrel files?
I can open a PR if you want to support this specific use case.

**Comment by beenotung** [comment] 2024-06-19 20:04
You suggestion works, I didn't think of determining the `to` value by checking the `importName + "/index"`. This can prevent it from adding `"/index.js"` instead of `".js"` when import name is already ending with `"/index"`.

This patch is released in fix-esm-import-path@1.8.0 :rocket: 

Please feel free to re-open the issue if the issue is not resolved

**Closed as completed by beenotung** 2024-06-19 20:04 UTC
